//
// Generated file, do not edit! Created by nedtool 5.6 from paquete.msg.
//

#ifndef __PAQUETE_M_H
#define __PAQUETE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>paquete.msg:1</tt> by nedtool.
 * <pre>
 * packet paquete
 * {
 *     int fromSource = false;
 *     int sequenceNumber;
 *     string source;
 *     int hopCount = 0;
 * 
 * }
 * </pre>
 */
class paquete : public ::omnetpp::cPacket
{
  protected:
    int fromSource;
    int sequenceNumber;
    ::omnetpp::opp_string source;
    int hopCount;

  private:
    void copy(const paquete& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const paquete&);

  public:
    paquete(const char *name=nullptr, short kind=0);
    paquete(const paquete& other);
    virtual ~paquete();
    paquete& operator=(const paquete& other);
    virtual paquete *dup() const override {return new paquete(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getFromSource() const;
    virtual void setFromSource(int fromSource);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual const char * getSource() const;
    virtual void setSource(const char * source);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const paquete& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, paquete& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PAQUETE_M_H

